--1
SELECT COUNT(*)
FROM votes
WHERE politician_id = '524';

--2
SELECT *
FROM votes v
INNER JOIN congress_members c
  ON v.politician_id = c.id;

--3
SELECT COUNT (*)
FROM votes v
INNER JOIN congress_members c
  ON v.politician_id = c.id
WHERE c.name like '%Erik Paulsen%';

--JAWABAN LAIN
SELECT COUNT(*)
FROM votes
WHERE politician_id = '339';

--4
SELECT A1.POLITICIAN_ID
     , A2.NAME
     , COUNT(A1.POLITICIAN_ID) AS RANK
FROM VOTES A1 INNER JOIN CONGRESS_MEMBERS A2
    ON A1.POLITICIAN_ID = A2.ID
GROUP BY A1.POLITICIAN_ID, A2.NAME
ORDER BY RANK DESC;

--5
SELECT A1.POLITICIAN_ID
     , A2.NAME
     , COUNT(A1.POLITICIAN_ID) AS RANK
FROM VOTES A1 INNER JOIN CONGRESS_MEMBERS A2
    ON A1.POLITICIAN_ID = A2.ID
GROUP BY A1.POLITICIAN_ID, A2.NAME
ORDER BY RANK ASC;

--RELEASE 2
--1.
SELECT FIRST_NAME ||' '||LAST_NAME || ' memilih ' || CM.NAME
FROM VOTERS V
INNER JOIN VOTES VT
  ON V.ID=VT.VOTER_ID
INNER JOIN CONGRESS_MEMBERS CM
  ON CM.ID = VT.POLITICIAN_ID
ORDER BY CM.NAME ASC;

--2.
SELECT CM.NAME, CM.LOCATION,CM.GRADE_CURRENT,COUNT(VT.POLITICIAN_ID) AS TOTAL_VOTES
FROM VOTERS V
INNER JOIN VOTES VT
  ON V.ID=VT.VOTER_ID
INNER JOIN CONGRESS_MEMBERS CM
  ON CM.ID = VT.POLITICIAN_ID
WHERE GRADE_CURRENT < 9
GROUP BY CM.NAME,CM.LOCATION,CM.GRADE_CURRENT
ORDER BY TOTAL_VOTES DESC;

--3
SELECT CM.NAME,CM.LOCATION,COUNT(VT.POLITICIAN_ID) AS TOTALVOTES
FROM VOTERS V INNER JOIN VOTES VT
  ON V.ID=VT.VOTER_ID
INNER JOIN CONGRESS_MEMBERS CM
  ON CM.ID = VT.POLITICIAN_ID
GROUP BY CM.NAME,CM.LOCATION,CM.GRADE_CURRENT
ORDER BY TOTALVOTES DESC;

--4
SELECT V.FIRST_NAME||' '||V.LAST_NAME,COUNT(VT.VOTER_ID) AS JUMLAH
FROM VOTERS V
INNER JOIN VOTES VT
  ON V.ID=VT.VOTER_ID
GROUP BY V.FIRST_NAME, V.LAST_NAME
HAVING JUMLAH>2
ORDER BY JUMLAH DESC;
